# Generated by Django 5.1.6 on 2025-02-17 16:25

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, verbose_name='title')),
                ('handle', models.SlugField(blank=True, max_length=100, verbose_name='handle')),
                ('is_main', models.BooleanField(default=False, verbose_name='is main menu')),
                ('menu_items', wagtail.fields.StreamField([('menu_category', 10), ('page_link', 12), ('url_link', 8)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': None, 'help_text': 'The menu item label as it will be seen in the menu', 'label': 'Label', 'max_length': 100, 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional. Used to reference this menu item in templates etc.', 'label': 'Handle', 'max_length': 100, 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'default': None, 'help_text': 'Optional. If provided it will override the page title in the menu item', 'label': 'Label', 'max_length': 100, 'required': False}), 3: ('wagtail.blocks.BooleanBlock', (), {'help_text': 'If checked the link will open in a new browser tab', 'label': 'Open in new tab', 'required': False}), 4: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'A link to an internal page of this site', 'label': 'Page', 'required': True}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional. A #hash or query string to append to the URL of the selected page', 'label': 'URL addition', 'max_length': 255, 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('label', 2), ('handle', 1), ('open_external', 3), ('page', 4), ('url_addition', 5)]], {}), 7: ('wagtail.blocks.URLBlock', (), {'help_text': 'A link to an custom url', 'required': True}), 8: ('wagtail.blocks.StructBlock', [[('label', 0), ('handle', 1), ('open_external', 3), ('url', 7)]], {}), 9: ('wagtail.blocks.StreamBlock', [[('page_link', 6), ('url_link', 8)]], {'required': False}), 10: ('wagtail.blocks.StructBlock', [[('label', 0), ('handle', 1), ('submenu_items', 9)]], {}), 11: ('wagtail.blocks.BooleanBlock', (), {'help_text': "If enabled, it will automatically generate a submenu from child pages of the menu item page which have the option 'Show in menus' selected", 'label': 'Add submenu', 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('label', 2), ('handle', 1), ('open_external', 3), ('page', 4), ('url_addition', 5), ('add_submenu', 11)]], {})}, verbose_name='menu items')),
                ('heading', models.CharField(blank=True, default='', max_length=255, verbose_name='heading')),
                ('submenu_levels', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2')], default=1, verbose_name='submenu levels')),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.site', verbose_name='site')),
            ],
            options={
                'verbose_name': 'menu',
                'verbose_name_plural': 'menus',
                'abstract': False,
                'unique_together': {('site', 'handle')},
            },
        ),
    ]
