# Generated by Django 5.1.6 on 2025-02-17 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
        ('nest', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='excerpt',
            field=models.TextField(blank=True, help_text='Optional. A short summary of the content to be used in previews and links. Optimal length is 200 characters', verbose_name='excerpt'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Optional. The main image representing the page. It will be used as cover and in links and previews both internal and external, like social media or search engines. Optimal recommended image size is 2400x1600px', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='nest.customimage', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='link_title',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='link title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='subtitle'),
        ),
    ]
